openapi: 3.0.3
info:
  title: Entertainment
  version: '1.0'
  contact:
    email: jmarroyave.compsci@gmail.com
    name: jmarroyave
  description: API for accessing entertainment options available in TV
servers:
  - url: 'http://localhost:8080/1.0/api'
paths:
  /dashboard:
    get:
      responses:
        '200':
          description: Successful request
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Dashboard'
      operationId: dashboardGet
      description: Returns the movies dashboard
components:
  schemas:
    Dashboard:
      type: object
      properties:
        last_update:
          description: Last time updated
          type: string
        people:
          description: Number of people
          type: number
        actors:
          description: Number of actors
          type: number
        directors:
          description: Number of directors
          type: number
        movies:
          description: Number of movies
          type: number
        countries:
          description: Distribution by country
          type: object
          additionalProperties:
            type: number
        genres:
          description: Distribution by genre
          type: object
          additionalProperties:
            type: number
        types:
          description: Distribution by type
          type: object
          additionalProperties:
            type: number
        years_released:
          description: Distribution by year released
          type: object
          additionalProperties:
            type: number
        years_added:
          description: Distribution by year added
          type: object
          additionalProperties:
            type: number
  securitySchemes: {}
  headers: {}
  responses: {}
  parameters: {}
security: []
